update for full mobile version ]
DevKaranJ/My-portfolio pull request #2
Opened 2023-06-02 22:14 UTC by DevKaranJ

2023-06-02 23:04 UTC, stanleySimeon requested changes
# Hi @DevKaranJ, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have a descriptive PR.
Kindly make sure you update your PR description before asking for another review.
 
Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-06-03 03:34 UTC, Felix45 requested changes
Hi @DevKaranJ, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif" width="350px" />

## Highlights :heavy_check_mark: 
- [x] Good UI design :white_check_mark: 
- [x]  Good use of CSS properties `grid` and `flexbox` in laying out the page :white_check_mark: 
- [x] No linter errors :white_check_mark: 
- [x] Pull request has a descriptive title and summary :white_check_mark: 
- [x] Repository has a professional readme file :white_check_mark: 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-03 03:34 UTC, Felix45 commented on index.html
> +        </section>
- [ Required ] I think there is some duplicated code on this page, the `works`, `about`, and `contact` sections appear twice on the same page. I believe this is not the desired outcome, please see the screenshot below and kindly rectify this.

## Screenshot 
![Screenshot from 2023-06-03 06-17-50](https://github.com/DevKaranJ/My-portfolio/assets/16392046/2e1a2c87-1e2d-425e-b14b-70c98eff373b)

2023-06-03 03:34 UTC, Felix45 commented on index.html
> +                        </p>
- [ Required ] I think it would be better if you used a `hx` tag on this subheading instead of the `p` tag, the `p` tag is usually used to markup multi-line text. I would like to suggest a `h3` tag for this section to be semantically correct.

2023-06-03 08:15 UTC, TadesseDev approved these changes
### Hi @DevKaranJ 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![giphy (1)](https://user-images.githubusercontent.com/69077061/212969210-69f495ba-f2fb-4559-a222-d1507310d6fb.gif)



## Highlights
 - [x] Good job making the changes requested by the previous code reviewer. ✅

## Optional suggestions

- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-03 08:15 UTC, merged